Transform: AWS::Serverless-2016-10-31
Description: URL Shortener Application

Globals:
  Function:
    Environment:
      Variables:
        TABLE_NAME: !Ref UrlShortenerTableName

Parameters:
  UrlShortenerTableName:
    Type: String
    Description: Name of the DynamoDB table for URL Shortener
    Default: UrlShortenerTable-SKR
  UrlApiGatewayName:
    Type: String
    Description: API Gateway Name
    Default: UrlShortenerApi-SKR
  UrlShortenerFunctionName:
    Type: String
    Description: Lambda Function Name for URL Shortener
    Default: UrlShortenerFunction-SKR
  ApiStageName:
    Type: String
    Description: API Gateway Stage Name
    Default: test
    AllowedValues: 
      - dev
      - test
      - prod

Resources:
  UrlApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref ApiStageName
      MethodSettings:
        - LoggingLevel: INFO
          DataTraceEnabled: true
          HttpMethod: "*"
      Name: !Ref UrlApiGatewayName

  UrlShortenerTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: !Ref UrlShortenerTableName
      PrimaryKey:
        Name: shortId
        Type: String

  UrlShortenerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      CodeUri: .
      Runtime: nodejs24.x
      FunctionName: !Ref UrlShortenerFunctionName
      Policies:
        - CloudWatchPutMetricPolicy: {}
        - DynamoDBCrudPolicy:
            TableName: !Ref UrlShortenerTableName
      Events:
        CreateShortUrlApi:
          Type: Api
          Properties:
            Path: /urlApi/get-url-shortener
            Method: post
            RestApiId: !Ref UrlApiGateway
        GetUrlApi:
          Type: Api
          Properties:
            Path: /urlApi/{shortId}
            Method: get
            RestApiId: !Ref UrlApiGateway
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: cjs
        Minify: false
        Target: node18
        EntryPoints:
          - src/index.ts
        External:
          - "@aws-sdk/client-dynamodb"
          - "aws-lambda"


Outputs:
  UrlShortenerTableName:
    Description: DynamoDB Table Name
    Value: !Ref UrlShortenerTable
  UrlShortenerTableArn:
    Description: DynamoDB Table ARN
    Value: !GetAtt UrlShortenerTable.Arn
  UrlShortenerFunctionArn:
    Description: Create Short URL Lambda Function ARN
    Value: !GetAtt UrlShortenerFunction.Arn
  ApiEndpoint:
    Description: API Gateway Endpoint URL
    Value: !Sub "https://${UrlApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod"
